### ISSUE TITLE
Error While Opening The App

### ISSUE THREAD

**Issue by PitchAbyss** [akai10tsuki/mkvbatchmultiplex#18]
i keep getting this error please help

![image](https://github.com/akai10tsuki/mkvbatchmultiplex/assets/13099434/f0dcd66d-4477-4f06-abf3-32eb1f03b99d)

[MKVBatchMultiplex.log](https://github.com/akai10tsuki/mkvbatchmultiplex/files/14327293/MKVBatchMultiplex.log)

**Comment by PitchAbyss** [comment]
> Hi,
> 
> What is the operating system you are running the program on?

Win 11 23H2 22631.3227

Though the older version works just not yhe latest one

**Comment by akai10tsuki** [comment]
Try [this version](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v3.0.0b1.dev0/MKVBatchMultiplex-3.0.0b2.dev0-portable.exe). I'm working the next release trying to embed the tools mainly for the Linux version.  In Linux works but for Windows the way the the permissions work on the install directories is not working.  There are many changes from the older version and this one all the tools used are new.  The version posted is a portable one. No installation is needed.

**Comment by PitchAbyss** [comment]
> Try [this version](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v3.0.0b1.dev0/MKVBatchMultiplex-3.0.0b2.dev0-portable.exe). I'm working the next release trying to embed the tools mainly for the Linux version. In Linux works but for Windows the way the the permissions work on the install directories is not working. There are many changes from the older version and this one all the tools used are new. The version posted is a portable one. No installation is needed.

awesome this one works flawlessly , this is amazing tool u made i wish its a great fixed update whenever u push it

**Comment by PitchAbyss** [comment]
> Try [this version](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v3.0.0b1.dev0/MKVBatchMultiplex-3.0.0b2.dev0-portable.exe). I'm working the next release trying to embed the tools mainly for the Linux version. In Linux works but for Windows the way the the permissions work on the install directories is not working. There are many changes from the older version and this one all the tools used are new. The version posted is a portable one. No installation is needed.

hi sir i dnt know why but when i run command though is says its generating files with "new" in begining but there are no signs of files

![image](https://github.com/akai10tsuki/mkvbatchmultiplex/assets/13099434/5de7c282-78b7-423a-8761-866ca4de98d9)

**Comment by IDontHaveIdea** [comment]
Hi,

Are you working with the [hotfix](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/tag/v3.0.0.1) version 3.0.0.1.  When I created the executables for version 3.0.0.0 I used the development branch of the project by mistake.

**Comment by PitchAbyss** [comment]
> Hi,
> 
> Are you working with the [hotfix](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/tag/v3.0.0.1) version 3.0.0.1.  When I created the executables for version 3.0.0.0 I used the development branch of the project by mistake.

Yes also please check last night i tried in vmware win 11 virtual machine and it never worked for me , can u please check

Are there any prerequisites to run this software ?

**Comment by akai10tsuki** [comment]
I don't have a windows 11 virtual machine. In a windows 10 virtual machine on vmware using the installer program it works fine for me. The prefix new- is pre-pended when there is a file with the same name on the destination directory.  Again using version 3.0.0.1 of the program.

The only requisite is to install MKVToolnix on the virtual machine.  I have not tested the embedded version on windows that much only on Linux.

Please attach the log file.  The file is in the  [.MKVBatchMultiplex] directory located in you home directory.

**Comment by PitchAbyss** [comment]
> I don't have a windows 11 virtual machine. In a windows 10 virtual machine on vmware using the installer program it works fine for me. The prefix new- is pre-pended when there is a file with the same name on the destination directory. Again using version 3.0.0.1 of the program.
> 
> The only requisite is to install MKVToolnix on the virtual machine. I have not tested the embedded version on windows that much only on Linux.
> 
> Please attach the log file. The file is in the [.MKVBatchMultiplex] directory located in you home directory.

@akai10tsuki @IDontHaveIdea i want to apologize it was just my faulty windows , all good now

**Comment by PitchAbyss** [comment]
> I don't have a windows 11 virtual machine. In a windows 10 virtual machine on vmware using the installer program it works fine for me. The prefix new- is pre-pended when there is a file with the same name on the destination directory. Again using version 3.0.0.1 of the program.
> 
> The only requisite is to install MKVToolnix on the virtual machine. I have not tested the embedded version on windows that much only on Linux.
> 
> Please attach the log file. The file is in the [.MKVBatchMultiplex] directory located in you home directory.

please test this if i rename a directory like this `abc's directory` the command doesnt work

![image](https://github.com/akai10tsuki/mkvbatchmultiplex/assets/13099434/c221e799-2f34-4326-b8a6-888f2d31d3f6)

error

![image](https://github.com/akai10tsuki/mkvbatchmultiplex/assets/13099434/eea710f0-d9c2-40fb-a937-11dde7331315)

**Comment by akai10tsuki** [comment]
Hi,

Internally the command that is used in windows is converted to unix style.  The unix style uses single quotes to work with filenames and directories that have a space in them.  The program internally changes the windows command to a unix style one this makes easier to work with and submit the command to the subprocess the executes the command.  Windows uses ("^) in the command and that really brakes the more complex regular expressions I use. Non-ansi characters also cause problems sometimes.

I will work on this now.

**Comment by PitchAbyss** [comment]
> Hi,
> 
> Internally the command that is used in windows is converted to unix style.  The unix style uses single quotes to work with filenames and directories that have a space in them.  The program internally changes the windows command to a unix style one this makes easier to work with and submit the command to the subprocess the executes the command.  Windows uses ("^) in the command and that really brakes the more complex regular expressions I use. Non-ansi characters also cause problems sometimes.
> 
> I will work on this now.

Awesome thankyou so much sir il keep testing and reporting if something else comes up ☺️

**Comment by akai10tsuki** [comment]
HI,

Try with with one of these [portable v3.0.0.1dev0](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v3.0.0.1/MKVBatchMultiplex-3.0.0.1dev0-portable.exe) or [installer v3.0.0.1dev0](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v3.0.0.1/MKVBatchMultiplex-3.0.0.1dev0-iss-AMD64.exe).

**Comment by PitchAbyss** [comment]
> HI,
> 
> Try with with one of these [portable v3.0.0.1dev0](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v3.0.0.1/MKVBatchMultiplex-3.0.0.1dev0-portable.exe) or [installer v3.0.0.1dev0](https://github.com/akai10tsuki/mkvbatchmultiplex/releases/download/v3.0.0.1/MKVBatchMultiplex-3.0.0.1dev0-iss-AMD64.exe).

absolutely amazing , thankyou so much sir works flawless now :D

**Comment by ossnorry** [comment]
Does this project still see development, I'm getting a similar error with the dev branch above and the main branch exe. 

Traceback (most recent call last):
  File "runApp.py", line 16, in <module>
  File "runApp.py", line 12, in main
  File "MKVBatchMultiplex\main.py", line 641, in mainApp
  File "MKVBatchMultiplex\config.py", line 203, in init
  File "vsutillib\files\classes\Configuration.py", line 477, in readFromFile
  File "xml\etree\ElementTree.py", line 529, in __init__
  File "xml\etree\ElementTree.py", line 569, in parse
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

###
Edit: clearing out all the file and a reinstall fixed it

**Comment by iamLazyCode** [comment]
> Does this project still see development, I'm getting a similar error with the dev branch above and the main branch exe. 
> 
> Traceback (most recent call last):
>   File "runApp.py", line 16, in <module>
>   File "runApp.py", line 12, in main
>   File "MKVBatchMultiplex\main.py", line 641, in mainApp
>   File "MKVBatchMultiplex\config.py", line 203, in init
>   File "vsutillib\files\classes\Configuration.py", line 477, in readFromFile
>   File "xml\etree\ElementTree.py", line 529, in __init__
>   File "xml\etree\ElementTree.py", line 569, in parse
> xml.etree.ElementTree.ParseError: no element found: line 1, column 0


I am latest 25h2 and works fine for me
